#@TYPE: Machine
#@NAME: Luckfox Lyra Plus
#@DESCRIPTION: RK3506G2 based Linux Micro Development Board
#https://www.luckfox.com/Luckfox-Lyra-Plus

require conf/machine/include/rk3506.inc

IMAGE_FSTYPES = "wic wic.zst tar.zst"


KERNEL_DEVICETREE ?= "rk3506g-luckfox-lyra-plus-sd.dtb"
MACHINE_EXTRA_RRECOMMENDS += "kernel-modules"
PREFERRED_PROVIDER_virtual/kernel = "linux-armbian"
EXTERNAL_KERNEL_DEVICETREE = "${DEPLOY_DIR_IMAGE}/devicetree"
KERNEL_DTC_FLAGS += "-@"


UBOOT_MACHINE = "luckfox-lyra-rk3506_defconfig"
UBOOT_EXTLINUX_ROOT = "root=/dev/mmcblk0p3"

WKS_FILE = "mini_partitions.wks.in"

MACHINE_FEATURES = " \
  rtc \
  screen \
  serial \
  usbgadget \
  usbhost \
  vfat \
"

KERNEL_FEATURES += " \
  cfg/fs/ext4.scc \
  features/cgroups/cgroups.scc \
"
