#@TYPE: Machine
#@NAME: Radxa Zero 3E
#@DESCRIPTION: The Radxa ZERO 3e is an ultra-small, high-performance single board computer based on the Rockchip RK3566, with a compact form factor, and rich interfaces.
#http://radxa.com/products/zeros/zero3e/

require conf/machine/include/radxa-zero-3.inc

IMAGE_FSTYPES = "wic wic.zst tar.zst"


KERNEL_DEVICETREE ?= "rockchip/rk3566-radxa-zero-3e.dtb"
PREFERRED_PROVIDER_virtual/kernel = "linux-torvalds"

UBOOT_EXTLINUX_KERNEL_ARGS += "rootwait rw rootfstype=ext4"
UBOOT_EXTLINUX_ROOT = "root=/dev/mmcblk0p${bootpart}"

WKS_FILE = "ota_partitions.wks.in"