#@TYPE: Machine
#@NAME: Radxa Zero 3E
#@DESCRIPTION: The Radxa ZERO 3e is an ultra-small, high-performance single board computer based on the Rockchip RK3566, with a compact form factor, and rich interfaces.
#http://radxa.com/products/zeros/zero3e/

require conf/machine/include/rk3566.inc

IMAGE_FSTYPES = "wic wic.zst tar.zst"


KERNEL_DEVICETREE ?= "rockchip/rk3566-radxa-zero-3e.dtb"
MACHINE_EXTRA_RRECOMMENDS += "kernel-modules"
PREFERRED_PROVIDER_virtual/kernel = "linux-torvalds"
EXTERNAL_KERNEL_DEVICETREE = "${DEPLOY_DIR_IMAGE}/devicetree"
KERNEL_DTC_FLAGS += "-@"

UBOOT_MACHINE = "radxa-zero-3-rk3566_defconfig"
UBOOT_EXTLINUX_KERNEL_ARGS += "rootwait rw rootfstype=ext4"
UBOOT_EXTLINUX_ROOT = "root=/dev/mmcblk0p${bootpart}"

WKS_FILE = "ota_partitions.wks.in"


MACHINE_FEATURES = " \
  bluetooth \
  rtc \
  screen \
  serial \
  touchscreen \
  usbgadget \
  usbhost \
  vfat \
  wifi \
"
