#@TYPE: Machine
#@NAME: Radxa Rock 5B+
#@DESCRIPTION: ROCK5+ is the 5th generation of SBC designed by Radxa.
#https://radxa.com/products/rock5/5bp

require conf/machine/include/rk3588.inc

IMAGE_FSTYPES = "wic wic.zst tar.zst"


KERNEL_DEVICETREE ?= "rockchip/rk3588-rock-5b-plus.dtb"
MACHINE_EXTRA_RRECOMMENDS += "kernel-modules"
PREFERRED_PROVIDER_virtual/kernel = "linux-torvalds"

UBOOT_MACHINE = "rock5b-rk3588_defconfig"
UBOOT_EXTLINUX_KERNEL_ARGS += "rootwait rw rootfstype=ext4"
UBOOT_EXTLINUX_ROOT = "${@bb.utils.contains('MACHINE_FEATURES', 'nvme_boot', 'root=/dev/nvme0n1p''$''{bootpart}', 'root=/dev/mmcblk0p''$''{bootpart}', d)}"


## Add "separate_bootloader" to MACHINE_FEATURES to create two separeted images. One with bootloader, second with rest of system.
do_rootfs[depends] += "${@bb.utils.contains('MACHINE_FEATURES', 'separate_bootloader', 'bootloader-image:do_image_complete', '', d)}"
WKS_FILE = "${@bb.utils.contains('MACHINE_FEATURES', 'separate_bootloader', 'ota_rootfs.wks.in', 'ota_partitions.wks.in', d)}"
