#@TYPE: Machine
#@NAME: Radxa Rock 5B+
#@DESCRIPTION: ROCK5+ is the 5th generation of SBC designed by Radxa.
#https://radxa.com/products/rock5/5bp

require conf/machine/include/common.inc
require conf/machine/include/rk3588.inc

CUSTOM_KERNEL_DEVICETREE ?= "rockchip/rk3588-rock-5b-plus.dtb"
MACHINE_EXTRA_RRECOMMENDS += "kernel-modules"

UBOOT_MACHINE = "rock5b-rk3588_defconfig"

PREFERRED_PROVIDER_virtual/kernel = "linux-collabora"

IMAGE_FSTYPES = "wic wic.zst tar.zst"
WKS_FILE = "ota_partitions.wks.in"

UBOOT_EXTLINUX_KERNEL_ARGS += "rootwait rw rootfstype=ext4"
UBOOT_EXTLINUX_ROOT = "root=/dev/mmcblk0p${bootpart}"
