#@TYPE: Machine
#@NAME: STM32MP157D-DK1
#@MAINTAINER: Marcin Bober <mbober1@gmail.com>

require conf/machine/include/stm32mp1.inc

KERNEL_DEVICETREE ?= "st/stm32mp157c-dk2.dtb"
KBUILD_DEFCONFIG ?= "multi_v7_defconfig"
KCONFIG_MODE = "--alldefconfig"

SPL_BINARY ?= "u-boot-spl.stm32"
UBOOT_MACHINE ?= "stm32mp15_basic_defconfig"
UBOOT_EXTLINUX ?= "1"
UBOOT_EXTLINUX_KERNEL_ARGS ?= "rootwait rw rootfstype=ext4"
UBOOT_EXTLINUX_ROOT ?= "root=/dev/mmcblk0p${bootpart}"
UBOOT_EXTLINUX_CONSOLE ?= "${SERIAL_CONSOLES}"
UBOOT_EXTLINUX_FDT ?= "../stm32mp157c-dk2.dtb"

# PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
PREFERRED_PROVIDER_virtual/kernel = "linux-torvalds"
INSANE_SKIP:linux-torvalds-src += "buildpaths"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += " \
    kernel-image \
    kernel-devicetree \
    kernel-modules \
    u-boot \
    linux-yocto-fitimage \
"

KERNEL_CLASSES += "kernel-fit-extra-artifacts"
KERNEL_IMAGETYPE ?= "Image"
RRECOMMENDS:${KERNEL_PACKAGE_NAME}-base = ""
KERNEL_DEPLOY_DEPEND ?= "linux-yocto-fitimage:do_deploy"

WKS_FILE = "stm32mp157-basic-ota.wks.in"
